# Smart WebView for iOS - Configuration
#
# --- Debug ---
# Enable debug mode for extra logging and test actions. Set to false for production.
debug.mode=false

# --- App & URLs ---
# The main URL your app will load.
app.url=https://hf.space

# The title of your application on the iPhone home screen
app.name=Synopus

# The local HTML file to show when the app is offline.
offline.url=offline.html

# The base URL for the search feature.
search.url=https://www.google.com/search?q=

# The suffix to append for the sharing feature.
share.url.suffix=/?share=

# A comma-separated list of domains that should NOT be opened externally.
external.url.exception.list=mgks.dev,docs.mgks.dev,mgks.github.io,hf.space

# --- Feature Flags ---
# Enable file uploads from a web form (<input type="file">).
feature.uploads=false

# Allow multiple file selection if the HTML input tag supports it.
feature.multiple.uploads=false

# Enable the pull-to-refresh gesture.
feature.pull.refresh=true

# Open external links in an external browser.
feature.open.external.urls=true

# --- Plugins ---
# Comma-separated list of plugins to enable. Case-sensitive.
plugins.enabled=Toast,Dialog

# Enable the Playground floating UI for testing plugins.
plugins.playground.enabled=false

# --- Permissions ---
# Comma-separated list of permission groups to request on launch.
permissions.on.launch=
